INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Cristal');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Tio Jorge');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Cisne');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Moinho Fino');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Três Corações');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Bambino');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Quero');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Pomarola');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Gomes da Costa');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Knorr');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Anglo');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Mabel');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Italac');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Lux');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Colgate');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Personal');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Omo');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Ype');
INSERT INTO `mydb`.`marcas` (`nome_marca`) VALUES ('Zupp');

INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('Arroz', 'saco de arroz', '1', '9');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('Feijão', 'saco de feijão', '1', '9');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('óleo de soja', 'litro de óleo de soja', '1', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('sal', 'saco de sal', '3', '13');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('açúcar', 'saco de açúcar', '1', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('café', 'café em pó', '6', '4');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('molho de tomate', 'molho de tomate enlatado', '7', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('macarrão espaguete', 'massa de macarrão ', '1', '14');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('sardinha', 'sardinha enlatada', '9', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('salsicha', 'salsicha enlatada', '11', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('milho', 'milho enlatado', '7', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('farinha de trigo', 'pacote de farinha de trigo', '1', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('biscoito doce', 'pacote de biscoito doce', '12', '7');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('leite em pó', 'pacote de leite em pó', '13', '6');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('sabonete', 'sabonete em barra', '14', '12');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('creme dental', 'tubo de creme dental', '15', '12');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('papel higiênico', 'pacote de papel higiênico', '16', '12');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('sabão em pó', 'pacote de sabão em pó', '17', '1');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('detergente líquido', 'frasco de detergente líquido', '18', '1');
INSERT INTO `mydb`.`produtos` (`nome_produto`, `descricao_produto`, `id_marca`, `id_categoria`) VALUES ('sabão em barra', 'pacote de sabão em barra', '19', '1');
