SELECT * FROM SUPERMERCADOS 
	INNER JOIN PRECO_PRODUTOS ON SUPERMERCADOS.ID_SUPERMERCADO = PRECO_PRODUTOS.ID_SUPERMERCADO 
	INNER JOIN PRODUTOS ON PRECO_PRODUTOS.ID_PRODUTO = PRODUTOS.ID_PRODUTO
  INNER JOIN MARCAS ON PRODUTOS.ID_MARCA = MARCAS.ID_MARCA;
