-- MySQL Script generated by MySQL Workbench
-- 10/19/18 22:17:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAISES` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(50) NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADOS` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(100) NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_ESTADOS_PAISES1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_ESTADOS_PAISES1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`PAISES` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADES` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(50) NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_CIDADES_ESTADOS1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_CIDADES_ESTADOS1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `mydb`.`ESTADOS` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(200) NULL,
  `cpf_cliente` VARCHAR(15) NULL,
  `telefone_cliente` VARCHAR(15) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `senha_cliente` VARCHAR(100) NULL,
  `data_nasc_cliente` DATE NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_CLIENTES_CIDADES_idx` (`id_cidade` ASC),
  CONSTRAINT `fk_CLIENTES_CIDADES`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`CIDADES` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPERMERCADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUPERMERCADOS` (
  `id_supermercado` INT NOT NULL AUTO_INCREMENT,
  `nome_supermercado` VARCHAR(100) NULL,
  `cnpj_supermercado` VARCHAR(20) NULL,
  `endereco_supermercado` TEXT NULL,
  `telefone_supermercado` VARCHAR(15) NULL,
  `email_supermercado` VARCHAR(100) NULL,
  `senha_supermercado` VARCHAR(100) NULL,
  `foto_supermercado` BLOB NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_supermercado`),
  INDEX `fk_SUPERMERCADOS_CIDADES1_idx` (`id_cidade` ASC),
  CONSTRAINT `fk_SUPERMERCADOS_CIDADES1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`CIDADES` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MARCAS` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(100) NULL,
  `descricao_marca` TEXT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIAS` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(100) NULL,
  `descricao_categoria` TEXT NULL,
  `foto_categoria` BLOB NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOS` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(50) NULL,
  `descricao_produto` TEXT NULL,
  `foto_produto` BLOB NULL,
  `id_marca` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_PRODUTOS_MARCAS1_idx` (`id_marca` ASC),
  INDEX `fk_PRODUTOS_CATEGORIAS1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_PRODUTOS_MARCAS1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`MARCAS` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTOS_CATEGORIAS1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRECO_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRECO_PRODUTOS` (
  `id_produto` INT NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `id_supermercado` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_supermercado`),
  INDEX `fk_PRODUTOS_has_SUPERMERCADOS_SUPERMERCADOS1_idx` (`id_supermercado` ASC),
  INDEX `fk_PRODUTOS_has_SUPERMERCADOS_PRODUTOS1_idx` (`id_produto` ASC),
  CONSTRAINT `fk_PRODUTOS_has_SUPERMERCADOS_PRODUTOS1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`PRODUTOS` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTOS_has_SUPERMERCADOS_SUPERMERCADOS1`
    FOREIGN KEY (`id_supermercado`)
    REFERENCES `mydb`.`SUPERMERCADOS` (`id_supermercado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
