SELECT SUPERMERCADOS.NOME_SUPERMERCADO AS Nome_do_Supermercado, PRODUTOS.NOME_PRODUTO AS Nome_do_Produto, MARCAS.NOME_MARCA AS Marca,  PRECO_PRODUTOS.PRECO_PRODUTO AS Preco_do_Produto FROM SUPERMERCADOS 
	INNER JOIN PRECO_PRODUTOS ON SUPERMERCADOS.ID_SUPERMERCADO = PRECO_PRODUTOS.ID_SUPERMERCADO 
	INNER JOIN PRODUTOS ON PRECO_PRODUTOS.ID_PRODUTO = PRODUTOS.ID_PRODUTO
  INNER JOIN MARCAS ON PRODUTOS.ID_MARCA = MARCAS.ID_MARCA;
